import Head from 'next/head';
import MainComponent from '../Components/MainComponent';
import Background from '../public/Background';

export default function Home() {
	return (
		<div className="min-h-screen mx-auto flex flex-col">
			<Head>
				<title>FOLDSCOPE Assignment</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<nav className="flex items-center justify-between flex-wrap bg-green-500 p-6">
				<div className="flex items-center flex-shrink-0 text-white mr-6">
					<span className="font-semibold text-xl tracking-tight">
						FOLDSCOPE
					</span>
				</div>
			</nav>
			<MainComponent />
		</div>
	);
}
